from dataclass.match.ban import Ban
from dataclass.match.baron import Baron
from dataclass.match.challenges import Challenges
from dataclass.match.champion import Champion
from dataclass.match.data import Data
from dataclass.match.dragon import Dragon
from dataclass.match.info import Info
from dataclass.match.inhibitor import Inhibitor
from dataclass.match.match import Match
from dataclass.match.metadata import Metadata
from dataclass.match.objectives import Objectives
from dataclass.match.participant import Participant
from dataclass.match.perks import Perks
from dataclass.match.riftHerald import RiftHerald
from dataclass.match.selection import Selection
from dataclass.match.statPerks import StatPerks
from dataclass.match.style import Style
from dataclass.match.team import Team
from dataclass.match.tower import Tower
